#!/bin/bash

# This script was originally created to gather a large number of files from a website. In its present configuration it is more geared at retreaving pictures, movies, and audio. If you are more interested in gathering the html files of a site PLEASE comment out the lines that are designed to delete the html data.

# Before running this script please note the comments around each section, they describe what each section does, and how to customize if for your specific needs.

echo " "
echo " "
echo " 			       - -	"
echo "			     { 0 0 }	"
echo "+------------------------oOOo--(_)--oOOo------------------------+"
echo "|								|"
echo "|		---The Web Site Download Script---		|"
echo "|								|"
echo "|			 * Written by: *			|"
echo "|								|"
echo "|		====  Laptopfreek0 & Chris Lanham	====	|"
echo "|								|"
echo "+---------------------------------------------------------------+"
echo " "
echo " "
echo "-Warning-!!! this script may take hours or even days to complete!!!"
echo " "
echo " --- Part 1: --- "
read -p "To start this script press any key, to abort hold Control + C"

echo " "
echo " " 

# These next two find commands are to clean up any existing index or html files that might cause the mirror to not update correctly (important when updating an existing mirror)
# It will search the current working directory for any html files as well as any downloads.* directories.
# These types of files are generated in each update of a previously mirrored website.
# If you want to keep all of the html files of your mirror it is important that you comment these find commands out !!!

find . -name '*html*' -print0 | xargs -0 rm -v
find . -name '*downloads.*' -print0 | xargs -0 rm -v

echo " "
echo " --- Part 2 ---"
read -p "To continue this script and start mirror process press any key ...to abort hold Control + C"
#
# Replace www.example.com with your own URL
# If the mirror does not need to use SSL, change the "https" to "http" 
# Also, if you are not using https the "--no-check-certificate" can be deleted
# If your site does not have a username or password delete the "--user=foo --password=bar"
# The -c argument is to continue a previous mirror of a website, it is best left on even if it is the first time a site is being mirrored
# The --limit-rate=1200k will limit the speed of the mirror to 1200 kb/s

wget -c -e --limit-rate=1200k robots=off -x --user=foo --password=bar -m --no-check-certificate https://example.com/exampleDirectory

echo "#=\+/=#-#=\+/=#-#=\+/=#-#=\+/=#-#=\+/=#-#=\+/=#-#=\+/=#-#=\+/=#"

# This section of the script is to clean any un-wanted html files generated by the mirroring process.
# If you would like to keep the generated html and html.download.* files choose "n" and hit enter at this prompt.
# After choosing "y" or "n" you must hit enter for the script to read your choice

echo "Do you want to delete the extra files ( y / n ) ?"

read a
if [[ $a == "N" || $a == "n" ]]; then
        echo "Ending script..."
else
        echo "Cleaning files..."

find . -name '*html*' -print0 | xargs -0 rm -v
find . -name '*downloads.*' -print0 | xargs -0 rm -v

fi

echo "end of script"
echo "#=\+/=#-#=\+/=#-#=\+/=#-#=\+/=#-#=\+/=#-#=\+/=#-#=\+/=#-#=\+/=#"
echo " "
read -p "Press any key to continue…"
